// Transcribed from Tables 1, 2, and 10 of MUNITE_submission.pdf.
// Preserve the reported precision. Values on different metrics are never pooled.
export const benchmarks = {
  poly: {
    name: 'PolyMNIST-D-Q',
    methods: ['MUNI', 'CFM', 'DFM', 'MUNITE'],
    metrics: [
      {
        route: '∅ → all five',
        label: 'Image fidelity · FD',
        direction: 'down',
        values: ['3.0407', '71.6626', '19.9587', '1.5230'],
      },
      {
        route: '∅ → all five',
        label: 'Digit coherence',
        direction: 'up',
        values: ['0.5799', '0.0237', '0.2973', '0.9826'],
      },
      {
        route: '∅ → all five',
        label: 'Quadrant coherence',
        direction: 'up',
        values: ['0.9041', '0.9902', '0.8222', '1.0000'],
      },
      {
        route: 'Digit → one view',
        label: 'Digit accuracy',
        direction: 'up',
        values: ['0.9843', '0.2402', '0.7224', '0.9941'],
      },
      {
        route: 'Quadrant → one view',
        label: 'Quadrant accuracy',
        direction: 'up',
        values: ['1.0000', '0.9936', '0.9372', '1.0000'],
      },
      {
        route: '(Digit, quadrant) → one view',
        label: 'Both-label accuracy',
        direction: 'up',
        values: ['0.9925', '0.2200', '0.7325', '0.9943'],
      },
      {
        route: 'Digit → three views',
        label: 'Quadrant coherence',
        direction: 'up',
        values: ['0.2528', '0.9879', '0.8798', '1.0000'],
      },
      {
        route: 'Quadrant → three views',
        label: 'Digit coherence',
        direction: 'up',
        values: ['0.1074', '0.1597', '0.4612', '0.9904'],
      },
    ],
  },
  ffhq: {
    name: 'FFHQ64',
    methods: ['MUNI', 'CFM', 'DFM', 'MUNITE'],
    metrics: [
      {
        route: '∅ → all five',
        label: 'RGB fidelity · FID',
        direction: 'down',
        values: ['34.618', '122.617', '55.840', '29.918'],
      },
      {
        route: '∅ → all five',
        label: 'Age coherence',
        direction: 'up',
        values: ['0.5630', '0.3068', '0.4546', '0.5692'],
      },
      {
        route: '∅ → all five',
        label: 'Gender coherence',
        direction: 'up',
        values: ['0.9596', '0.7328', '0.8658', '0.9610'],
      },
      {
        route: '∅ → all five',
        label: 'RGB–segmentation coherence',
        direction: 'up',
        values: ['0.7762', '0.7357', '0.8084', '0.8896'],
      },
      {
        route: '∅ → all five',
        label: 'RGB–normal error',
        direction: 'down',
        values: ['0.0700', '0.0603', '0.0495', '0.0491'],
      },
      {
        route: 'Age → RGB',
        label: 'Age accuracy',
        direction: 'up',
        values: ['0.5204', '0.2506', '0.4002', '0.6274'],
      },
      {
        route: 'Gender → RGB',
        label: 'Gender accuracy',
        direction: 'up',
        values: ['0.9684', '0.6944', '0.8518', '0.9790'],
      },
      {
        route: '(Age, gender) → RGB',
        label: 'Both-label accuracy',
        direction: 'up',
        values: ['0.5100', '0.1842', '0.3690', '0.5898'],
      },
      {
        route: '(Age, gender) → RGB, seg., normals',
        label: 'RGB–segmentation coherence',
        direction: 'up',
        values: ['0.6038', '0.7441', '0.8142', '0.8888'],
      },
      {
        route: '(Age, gender) → RGB, seg., normals',
        label: 'RGB–normal error',
        direction: 'down',
        values: ['0.1106', '0.0572', '0.0492', '0.0500'],
      },
    ],
  },
  ita: {
    name: 'Image–text–audio',
    methods: ['CoDi', 'OmniFlow', 'MUNI', 'CFM', 'DFM', 'FlowBind', 'MUNITE'],
    metrics: [
      {
        route: 'Text → (image, audio)',
        measure: 'AIS',
        observed: 'Text',
        targets: ['image', 'audio'],
        label: 'Image–audio coherence · AIS',
        direction: 'up',
        values: ['63.866', '77.027', '81.558', '74.702', '73.635', '79.819', '83.336'],
      },
      {
        route: 'Image → (text, audio)',
        measure: 'CLAP',
        observed: 'Image',
        targets: ['text', 'audio'],
        label: 'Text–audio coherence · CLAP',
        direction: 'up',
        values: ['7.418', '14.781', '32.237', '21.695', '20.951', '25.812', '34.762'],
      },
      {
        route: 'Audio → (text, image)',
        measure: 'CLIP',
        observed: 'Audio',
        targets: ['text', 'image'],
        label: 'Text–image coherence · CLIP',
        direction: 'up',
        values: ['23.414', '22.697', '25.850', '24.034', '24.037', '24.853', '26.334'],
      },
      {
        route: '∅ → all three',
        measure: 'CLIP',
        observed: null,
        targets: ['text', 'image'],
        label: 'Text–image coherence · CLIP',
        direction: 'up',
        values: [null, '21.17', '26.949', '23.622', '23.740', null, '27.398'],
      },
      {
        route: '∅ → all three',
        measure: 'CLAP',
        observed: null,
        targets: ['text', 'audio'],
        label: 'Text–audio coherence · CLAP',
        direction: 'up',
        values: [null, '14.23', '28.467', '19.896', '19.503', null, '30.220'],
      },
      {
        route: '∅ → all three',
        measure: 'AIS',
        observed: null,
        targets: ['image', 'audio'],
        label: 'Image–audio coherence · AIS',
        direction: 'up',
        values: [null, '50.95', '81.989', '74.208', '71.942', null, '87.045'],
      },
    ],
  },
};

export const coherenceExamples = {
  quadrant: {
    input: 'Bottom-left quadrant',
    unobserved: 'digit',
    muni: '0.1074',
    munite: '0.9904',
    independent: '0.1014',
    chance: '0.10',
  },
  digit: {
    input: 'Digit 1',
    unobserved: 'quadrant',
    muni: '0.2528',
    munite: '1.0000',
    independent: '0.2500',
    chance: '0.25',
  },
};

export const gallery = {
  unconditional: {
    name: 'Unconditional',
    figure: 12,
    description: 'No modality is observed. An image, a caption and a sound are generated together.',
    samples: [
      {
        image: 'Im12-Im1',
        text: 'The sun sets over a town on the coast.',
        audio: 'ocean waves, wind',
        id: 13,
      },
      {
        image: 'Im12-Im2',
        text: 'a wolf howling with light rustling in the background',
        audio: 'canine howling',
        id: 14,
      },
      {
        image: 'Im12-Im3',
        text: 'Two dogs that are looking at each other.',
        audio: 'dogs barking',
        id: 15,
      },
      {
        image: 'Im12-Im4',
        text: 'A painting of a woman sitting at a table.',
        audio: 'dishes and cutlery',
        id: 16,
      },
      {
        image: 'Im12-Im5',
        text: 'A bird sitting on top of a tree branch.',
        audio: 'wings flapping',
        id: 17,
      },
    ],
  },
  text: {
    name: 'Text → image + audio',
    figure: 13,
    description: 'Text is observed. An image and a sound are generated together.',
    samples: [
      {
        image: 'Im13-Im1',
        input: 'vibrations from a sewing machine',
        audio: 'sewing machine',
        id: 23,
      },
      {
        image: 'Im13-Im2',
        input: 'a fire siren with people talking',
        audio: 'fire-truck siren, speech',
        id: 24,
      },
      {
        image: 'Im13-Im3',
        input: 'a woman speaks followed by birds chirping',
        audio: 'birds chirping, speech',
        id: 25,
      },
      {
        image: 'Im13-Im4',
        input: 'an aircraft engine is taking off',
        audio: 'aircraft engine',
        id: 26,
      },
      {
        image: 'Im13-Im5',
        input: 'a series of bell chimes and ringing',
        audio: 'church bells ringing',
        id: 27,
      },
    ],
  },
  image: {
    name: 'Image → text + audio',
    figure: 13,
    description: 'An image is observed. A caption and a sound are generated together.',
    samples: [
      { image: 'Im13-Im11', text: 'a bell rings continuously', audio: 'bell ringing', id: 28 },
      {
        image: 'Im13-Im12',
        text: 'A horse is standing in the grass with lightning behind it.',
        audio: 'thunder and rain',
        id: 29,
      },
      { image: 'Im13-Im13', text: 'a clock tick-tocks', audio: 'clock ticking', id: 30 },
      {
        image: 'Im13-Im14',
        text: 'a person is typing on a computer keyboard',
        audio: 'keyboard typing',
        id: 31,
      },
      {
        image: 'Im13-Im15',
        text: 'A bathroom with an empty toilet and white walls.',
        audio: 'toilet flushing',
        id: 32,
      },
    ],
  },
  audio: {
    name: 'Audio → text + image',
    figure: 13,
    description: 'A sound is observed. A caption and an image are generated together.',
    samples: [
      {
        image: 'Im13-Im26',
        text: 'church bells ringing in the distance',
        audio: 'church bells ringing',
        id: 33,
        audioObserved: true,
      },
      {
        image: 'Im13-Im27',
        text: 'a group of ducks quacking as a crowd of people talk in the background',
        audio: 'ducks quacking, speech',
        id: 34,
        audioObserved: true,
      },
      {
        image: 'Im13-Im28',
        text: 'a man gives a speech then an audience gives applause',
        audio: 'speech, applause',
        id: 35,
        audioObserved: true,
      },
      {
        image: 'Im13-Im29',
        text: 'a man speaks while a guitar is played followed by someone briefly talking',
        audio: 'speech, guitar',
        id: 36,
        audioObserved: true,
      },
      {
        image: 'Im13-Im30',
        text: 'frogs croak and crickets chirp in the background',
        audio: 'frogs croaking',
        id: 37,
        audioObserved: true,
      },
    ],
  },
};
